# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e5b6128ed741ea859002c593b31a7c8c3ac78ab0586d1c0f38fad1701d86674c1356ecafbe3717a56e11f8d760e8f580d2a4509fa9888cebd7c465d52d02d5b

test:
  secret_key_base: 4364c351209e2187e7aa82fa71d42065bcd228de58007d66a41fd5cbe8383591ee0372b3ce1df258efbd3c25938e7fa79fe0d1b5604fa3a9a23b4599c8ae049b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
